name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo.git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}

      - name: Build server
        run: cargo build --manifest-path server/Cargo.toml --release
      - name: Upload server artifact
        uses: actions/upload-artifact@v2
        with:
          name: wanhope-server
          path: target/release/server

